const assert = require('assert');
const fs = require('fs');
const path = require('path');

// 1. Check generated HTML file directly
const htmlPath = path.join(__dirname, '..', '_site', 'songs', 'sketches', 'sight-reading', 'index.html');
assert(fs.existsSync(htmlPath), '_site/songs/sketches/sight-reading/index.html must exist');

const htmlContent = fs.readFileSync(htmlPath, 'utf-8');

console.log('Testing Server-Rendered HTML Song Combobox...');

// Assert input element is pre-populated with initial song value
const inputMatch = htmlContent.match(/<input[^>]*id="trainer-song"[^>]*>/);
assert(inputMatch !== null, 'Found trainer-song input element in HTML');
const inputHtml = inputMatch[0];

assert(/value="[^"]+"/.test(inputHtml) && !inputHtml.includes('value=""'), `Input element must contain pre-rendered song value attribute (got: ${inputHtml})`);

// Assert clear button has 'visible' class pre-rendered
const clearMatch = htmlContent.match(/<button[^>]*id="song-clear"[^>]*>/);
assert(clearMatch !== null, 'Found song-clear button in HTML');
assert(clearMatch[0].includes('visible'), 'song-clear button must have "visible" class in static HTML');

// Assert song list UL is pre-populated with LI options
const ulMatch = htmlContent.match(/<ul[^>]*id="song-list"[^>]*>(.*?)<\/ul>/s);
assert(ulMatch !== null, 'Found song-list UL element in HTML');
const ulInner = ulMatch[1];

assert(ulInner.includes('<li data-value="">Random</li>'), 'UL must contain Random option');
assert(ulInner.includes('class="selected"'), 'UL must contain a selected LI option');

console.log('PASS: Static HTML pre-renders initial song value and combobox options');
console.log(`  Rendered input tag: ${inputHtml}`);
console.log(`  Rendered clear button: ${clearMatch[0]}`);

// 2. Load actual songs.json file generated by Eleventy
const songsJsonPath = path.join(__dirname, '..', '_site', 'songs', 'sight-reading', 'songs.json');
assert(fs.existsSync(songsJsonPath), '_site/songs/sight-reading/songs.json exists');

let songsData = [];
for (let attempt = 0; attempt < 10; attempt++) {
  try {
    const raw = fs.readFileSync(songsJsonPath, 'utf-8');
    if (raw && raw.trim().endsWith(']')) {
      songsData = JSON.parse(raw);
      break;
    }
  } catch (_) {}
}
assert(Array.isArray(songsData) && songsData.length > 0, 'songs.json has valid song entries');

// 3. Test Combobox DOM Runtime Population & LocalStorage
function createMockElement(tagName = 'div', id = '') {
  const children = [];
  const classes = new Set();
  const attributes = {};
  const dataset = {};

  return {
    tagName: tagName.toUpperCase(),
    id: id,
    children: children,
    classList: {
      add: (cls) => classes.add(cls),
      remove: (cls) => classes.delete(cls),
      toggle: (cls, force) => {
        if (force !== undefined) {
          if (force) classes.add(cls); else classes.delete(cls);
        } else {
          if (classes.has(cls)) classes.delete(cls); else classes.add(cls);
        }
      },
      contains: (cls) => classes.has(cls),
    },
    dataset: dataset,
    value: '',
    placeholder: '',
    appendChild: function (child) {
      children.push(child);
      return child;
    },
  };
}

const inputEl = createMockElement('input', 'trainer-song');
const listEl = createMockElement('ul', 'song-list');
const clearEl = createMockElement('button', 'song-clear');

function populateAndSetupCombobox(songs) {
  listEl.children.length = 0;
  
  const randomLi = createMockElement('li');
  randomLi.textContent = 'Random';
  randomLi.dataset.value = '';
  listEl.appendChild(randomLi);

  songs.forEach((s) => {
    const li = createMockElement('li');
    const displayTitle = s.title || s.id;
    li.textContent = displayTitle;
    li.dataset.value = displayTitle;
    listEl.appendChild(li);
  });

  const firstTitle = songs.length > 0 ? (songs[0].title || songs[0].id) : '';

  let selectedValue = firstTitle || '';
  if (selectedValue) {
    inputEl.value = selectedValue;
    inputEl.placeholder = '';
    clearEl.classList.add('visible');
  } else {
    inputEl.value = '';
    inputEl.placeholder = 'Random';
    clearEl.classList.remove('visible');
  }

  listEl.children.forEach((li) => {
    li.classList.toggle('selected', li.dataset.value === selectedValue);
  });

  return { selectedValue, firstTitle };
}

const { selectedValue, firstTitle } = populateAndSetupCombobox(songsData);

assert.strictEqual(songsData.length > 0, true, 'At least 1 song in songs.json');
assert.strictEqual(firstTitle, songsData[0].title, 'First song title matches songs.json');
assert.strictEqual(inputEl.value, firstTitle, `Input value must equal first song title ("${firstTitle}")`);
assert.strictEqual(inputEl.placeholder, '', 'Input placeholder must be empty when song is selected');
assert.strictEqual(clearEl.classList.contains('visible'), true, 'Clear button must be visible when song is selected');
assert.strictEqual(listEl.children.length, songsData.length + 1, 'Song list populated with Random + all songs');

const selectedLi = listEl.children.find(li => li.classList.contains('selected'));
assert(selectedLi !== undefined, 'A song item in list is selected');
assert.strictEqual(selectedLi.dataset.value, firstTitle, 'Selected li dataset value matches first song title');

// 4. Test LocalStorage Persistence & Clear Button
const mockLocalStorage = {};
global.localStorage = {
  getItem: (key) => mockLocalStorage[key] !== undefined ? mockLocalStorage[key] : null,
  setItem: (key, val) => { mockLocalStorage[key] = String(val); },
  removeItem: (key) => { delete mockLocalStorage[key]; },
};

function selectItem(value) {
  if (value) {
    global.localStorage.setItem('tape-song', value);
    inputEl.value = value;
    inputEl.placeholder = '';
    clearEl.classList.add('visible');
  } else {
    global.localStorage.setItem('tape-song', '');
    inputEl.value = '';
    inputEl.placeholder = 'Random';
    clearEl.classList.remove('visible');
  }
}

// Select a specific song
selectItem('Jingle Bells');
assert.strictEqual(global.localStorage.getItem('tape-song'), 'Jingle Bells', 'localStorage saves selected song');
assert.strictEqual(inputEl.value, 'Jingle Bells', 'Input displays selected song');
assert.strictEqual(clearEl.classList.contains('visible'), true, 'Clear button visible for selected song');

// Clear selection with 'x' button
selectItem('');
assert.strictEqual(global.localStorage.getItem('tape-song'), '', 'localStorage cleared when clear button pressed');
assert.strictEqual(inputEl.value, '', 'Input cleared');
assert.strictEqual(inputEl.placeholder, 'Random', 'Placeholder reverts to Random');
assert.strictEqual(clearEl.classList.contains('visible'), false, 'Clear button hidden when selection cleared');

console.log('PASS: LocalStorage selection and clear button function correctly');
console.log('\nAll song selector unit tests PASSED.');
